### ISSUE TITLE
jupyternbextension-not found

### ISSUE THREAD

**Issue by Jungian1972** [iot-salzburg/gpu-jupyter#118]
Hey there,

When I attempt to spin up the container I get the following:

 => ERROR [gpu-jupyter 22/34] RUN git clone https://github.com/PAIR-code/facets.git &&     jupyter nbextension in  5.0s

Followed somewhat later by:
Jupyter command `jupyter-nbextension` not found.
------
failed to solve: process "/bin/bash -o pipefail -c git clone https://github.com/PAIR-code/facets.git &&     jupyter nbextension install facets/facets-dist/ --sys-prefix &&     rm -rf /tmp/facets &&     fix-permissions \"${CONDA_DIR}\" &&     fix-permissions \"/home/${NB_USER}\"" did not complete successfully: exit code: 1

Very new to this world so forgive me if it is something obvious.

--Paul

**Comment by fredrik-hansen** [comment]
Hi Jungian1972,
nbextension installations using jupyter command are deprecated, remove and install using pip or conda instead.
Facets repo seems stalled, I removed it entirely. Same goes for nvtop which you can safely remove.
After that you should be able to build the container succesfully.

**Comment by nareshmahato332** [comment]
@fredrik-hansen can you share the steps to fix this issue ?

**Comment by hann-sch** [comment]
Hi,
I ran into the same issue, I could figure out a workaround by copying the 
`src/Dockerfile.usefulpackages` https://github.com/iot-salzburg/gpu-jupyter/blob/master/generate-Dockerfile.sh#L115-L125 before the copying of
`$STACKS_DIR/scipy-notebook/Dockerfile` https://github.com/iot-salzburg/gpu-jupyter/blob/master/generate-Dockerfile.sh#L87-L92 in the `.generate-Dockerfile.sh`
At least the image was then successfully generated

**Comment by fredrik-hansen** [comment]
> @fredrik-hansen, I am also facing the same issue. can you share the steps to fix this issue ?

I did actually skip the generate-Dockerfile.sh entirely once I figured out the extension setups come from other repos pulled by that script(docker-stacks if I'm not mistaken), but also since I modified some other things;

Running on a newer image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

Added langchain, sentence_transformers, accelerate, prodigy, spacy, huggingface_hub, jupyter-ai and probably some more that I find useful, along with removal of some modules I never used. 
The prodigy license, I have yet to figure out how to set it up better, as current RUN pip install prodigy -f https://XXXX-XXXX-XXXX-XXXX@download.prodi.gy will leak my license key.

I also changed various things after running a security check using Grype on my docker image: 
docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock  --name Grype anchore/grype:latest digitalcompanion/gpu-jupyter:v2.4.5 >>SECURITY202308.md - it's worth checking your images for obvious and easy-to-fix vulnerabilities such as old versions of python modules.

I also created a helm chart for easy deploy and version tracking in my Kubernetes. 

I'd be happy to contribute the above changes to the respective repos, just did the above as a quick-fix to get on with my work.

**Comment by DonnyVerduijn** [comment]
> > @fredrik-hansen, I am also facing the same issue. can you share the steps to fix this issue ?
> 
> I did actually skip the generate-Dockerfile.sh entirely once I figured out the extension setups come from other repos pulled by that script(docker-stacks if I'm not mistaken), but also since I modified some other things;
> 
> Running on a newer image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
> 
> Added langchain, sentence_transformers, accelerate, prodigy, spacy, huggingface_hub, jupyter-ai and probably some more that I find useful, along with removal of some modules I never used. The prodigy license, I have yet to figure out how to set it up better, as current RUN pip install prodigy -f https://XXXX-XXXX-XXXX-XXXX@download.prodi.gy will leak my license key.
> 
> I also changed various things after running a security check using Grype on my docker image: docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock --name Grype anchore/grype:latest digitalcompanion/gpu-jupyter:v2.4.5 >>SECURITY202308.md - it's worth checking your images for obvious and easy-to-fix vulnerabilities such as old versions of python modules.
> 
> I also created a helm chart for easy deploy and version tracking in my Kubernetes.
> 
> I'd be happy to contribute the above changes to the respective repos, just did the above as a quick-fix to get on with my work.

Can you make a PR?

**Comment by fredrik-hansen** [comment]
> > > @fredrik-hansen, I am also facing the same issue. can you share the steps to fix this issue ?
> > 
> > 
> > I did actually skip the generate-Dockerfile.sh entirely once I figured out the extension setups come from other repos pulled by that script(docker-stacks if I'm not mistaken), but also since I modified some other things;
> > Running on a newer image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
> > Added langchain, sentence_transformers, accelerate, prodigy, spacy, huggingface_hub, jupyter-ai and probably some more that I find useful, along with removal of some modules I never used. The prodigy license, I have yet to figure out how to set it up better, as current RUN pip install prodigy -f https://XXXX-XXXX-XXXX-XXXX@download.prodi.gy will leak my license key.
> > I also changed various things after running a security check using Grype on my docker image: docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock --name Grype anchore/grype:latest digitalcompanion/gpu-jupyter:v2.4.5 >>SECURITY202308.md - it's worth checking your images for obvious and easy-to-fix vulnerabilities such as old versions of python modules.
> > I also created a helm chart for easy deploy and version tracking in my Kubernetes.
> > I'd be happy to contribute the above changes to the respective repos, just did the above as a quick-fix to get on with my work.
> 
> Can you make a PR?

I find that hard, due to the fact that the original repo pulls from another upstream source, which caused the issue in the first place.
I've since stopped using the Dockerfile generation script, so I believe a PR would be misplaced in this repo. Fixing the upstream one should be the smarter move, I figure?

**Comment by fredrik-hansen** [comment]
Changing the below to another, more recent version is likely to fix the issue and still retaining the structure of this repo:
# please test the build of the commit in https://github.com/jupyter/docker-stacks/commits/master in advance
export HEAD_COMMIT="efa95c2c5b9b095247cd2f5e55bc3b38c85da335"


If you find a more recent version that works well, please update here since even the path I took works, is far from ideal and I'd like to contribute to the original project instead of trying to maintain my own fork.
Best,

**Comment by ChristophSchranz** [comment]
Hi @Jungian1972,
thanks for noting this issue. The new command is `jupyter nbclassic-extension install` which is caused by and also changed by [docker-stacks](https://github.com/jupyter/docker-stacks). Their change is automatically adapted in gpu-jupyter with a new build:

https://github.com/iot-salzburg/gpu-jupyter/blob/78a107932cbd8c5be3ed5b43ccaf7c4ed915fb76/.build/Dockerfile#L356-L362

This issue should be solved with the new build in https://github.com/iot-salzburg/gpu-jupyter/pull/124.

**Comment by ChristophSchranz** [comment]
> Changing the below to another, more recent version is likely to fix the issue and still retaining the structure of this repo:
> 
> '''please test the build of the commit in https://github.com/jupyter/docker-stacks/commits/master in advance export HEAD_COMMIT="efa95c2c5b9b095247cd2f5e55bc3b38c85da335" '''
> 
> If you find a more recent version that works well, please update here since even the path I took works, is far from ideal and I'd like to contribute to the original project instead of trying to maintain my own fork. Best,

Hi @fredrik-hansen, that's a recommended way to adapt this issue. There are dependencies to docker-stacks - an important and challenging project to maintain - where older commit hashes still work. Now, this issue is fixed with https://github.com/iot-salzburg/gpu-jupyter/pull/124 that inherits the solution from a later docker-stacks commit.
