### ISSUE TITLE
Quickstart GPU support

### ISSUE THREAD

**Issue by Jollyhrothgar** [iot-salzburg/gpu-jupyter#29]
The quickstart setup for GPU support is missing a flag for docker: --gpus all.

I had to do (modified for my system config)

```bash
docker run -d -it --gpus all -p 8848:8888 -v /home/${USER}/workspace:/home/jovyan/work -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes --user root --restart always --name gpu-jupyter_1 gpu-jupyter```

**Comment by mathematicalmichael** [comment]
yup. https://github.com/iot-salzburg/gpu-jupyter/issues/16#issuecomment-657639689
thought this was taken care of... but the README will go through a big update as part of #27 in the next month or two, and I'll make sure to fix that. 

One of the things I think I'll try is set up a CI test that finds all `docker run` commands in the README and tests them for validity. bit tricky since github's servers don't have GPUs though, so I'm not entirely sure that'll work. 

thanks for the issue, we'll be sure to address it!

**Comment by ChristophSchranz** [comment]
Ohh sorry that was my fault!

Would it be a good idea to update the command in an own commit, as the description is currently not up to date?

**Comment by ChristophSchranz** [comment]
I've updated the parameter `--gpu all` in 346f1d4bd7ba90f1853fd656bfb03e548bea93e8.

I think we can close this issue now.
