### ISSUE TITLE
Is removing llvmlite 0.38 safe?

### ISSUE THREAD

**Issue by pcasagranda** [iot-salzburg/gpu-jupyter#70]
I'm using this excellent docker image for tests. 
Installing huggingface asrecognition fails, as it requires llvmlite-0.36.0-cp39-cp39-manylinux2010_x86_64. However, even the gpu-jupyter generated as "slim" (--slim) includes llvmlite 0.38, which cannot be uninstalled with pip. 

I removed it with conda. Is it safe or you can suggest other solutions?

**Comment by ChristophSchranz** [comment]
Hi @pcasagranda 
I'm glad you like it! :)

llvmite is installed because it is part of the anaconda-toolstack that is stacked into this installation. I'm not sure if this is safe. I suppose the anaconda toolstack tries to install the latest version that is compatible with the other toolstack. So downgrading  will be in many cases okay. Expecially if you do so by conda, it automatically will run some tests.
And in case it doesn't, you can't crash your host system within the docker-container 😉
