### ISSUE TITLE
Problem with Tensorflow GPU  

### ISSUE THREAD

**Issue by bklippstein** [iot-salzburg/gpu-jupyter#9]
```
# confirm TensorFlow sees the GPU
import tensorflow
from tensorflow.python.client import device_lib
assert 'GPU' in str(device_lib.list_local_devices())
```
--> no problem

```
# just try
import tensorflow as tf
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))
```
--> 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-ff2f78fb99cd> in <module>
      6     c = tf.matmul(a, b)
      7 
----> 8 with tf.Session() as sess:
      9     print (sess.run(c))

AttributeError: module 'tensorflow' has no attribute 'Session'
```
a solution might be
```
pip install --upgrade --force-reinstall tensorflow-gpu
```
(but it did't worked for me in a child docker image)

```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```

```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 891693182611328360
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 4840590997946823616
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 5618991104
locality {
  bus_id: 1
  links {
  }
}
incarnation: 11947021443223061618
physical_device_desc: "device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 16370588895216994843
physical_device_desc: "device: XLA_GPU device"
]
```
PyTorch on GPU via CUDA works fine

**Comment by maresb** [comment]
Try replacing `import tensorflow as tf` with `import tensorflow.compat.v1 as tf`.

More generally, take a look at https://www.tensorflow.org/guide/migrate

**Comment by ChristophSchranz** [comment]
Thanks for the feedback, this bug should be fixed with [commit: Fixed cuda compatibility issue in tf](e894fd0e9ccd581015d090c0386c644d22b32799).

See:
https://github.com/iot-salzburg/gpu-jupyter/blob/953983162232e789d67b895c14f95cb2a275ebd3/src/Dockerfile.gpulibs#L3-L8

As explained in the referenced [link](https://www.tensorflow.org/install/gpu),
"TensorFlow supports CUDA 10.1 (TensorFlow >= 2.1.0)". With Tensorflow 2.1 is should work.

By the way, in [extra/Getting_Started/GPU-processing.ipynb ](https://github.com/iot-salzburg/gpu-jupyter/blob/master/extra/Getting_Started/GPU-processing.ipynb) you can see the expected results for CUDA availability.

**Comment by bklippstein** [comment]
Thank you!! Tensorflow & Keras are working now. This image is a perfect base for a child image because all the heavy problems are solved in one black box. Much better than my old solution :-)

**Comment by ChristophSchranz** [comment]
@bklippstein you are welcome! :blush: 
Whenever you find a way how to improve this image, let me know by writing an issue or pull request!
